name: docker-evaluation
services:
  backdrop:
    build:
      context: ./1/apache
    ports:
      - 8088:80
    environment:
      BACKDROP_DB_HOST: db
      BACKDROP_DB_USER: backdrop
      BACKDROP_DB_PASSWORD: backdrop
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mysql
    environment:
      MYSQL_USER: backdrop
      MYSQL_PASSWORD: backdrop
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: backdrop
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 6s
      retries: 10
